HanSooSan/index.js

키보드,  수열의 경우수, 최댓값위치, 각 행의 최댓값, 각 열의 최댓값
---
키보드 
set, 배열 활용으로 각각 풀었으며,
대문자로 통일해서 set혹은 배열에 유일값만 넣어주고 그 값과
shift를 사용하는지 여부 확인해서 1을 더한 값을 도출
수열 경우의수
top 배열에 봉우리 (양 옆이 작은) 숫자 인덱스 번호를 추가
그 인덱스에서 왼쪽 오른쪽으로 이동하며 횟수를 카운트
왼 카운트 * 오 카운트 + 1 (봉우리 숫자) 하여 하나의 봉우리에 나올 수 있는 수열의 경우의 수 파악
모든 경우의 수를 합쳐줌
최대값 위치
이중 포문으로 하나씩 돌면서 answer과 maxNum을 업데이트 해준다.
행과 열이 1행 1열로 시작하기에 answer에 넣을 때에는 1씩 추가해준다.
각 행의 최대값
이중 for문 돌면서 각 행에서 maxNum을 업데이트 해주고 행이 바뀔 때 answer에 maxNum을 넣어준다.
행이 바뀌면 maxNum을 초기화하고 반복한다.
각 열의 최대값
각 행의 최대값과 같은 풀이 방식
---

키보드,  수열의 경우수, 최댓값위치, 각 행의 최댓값, 각 열의 최댓값

---

LeeEunYoung/230511/2차원배열-04-격자판최대합.js
LeeEunYoung/230511/2차원배열-05-스카이라인.js
LeeEunYoung/230511/2차원배열-06-봉우리.js
LeeEunYoung/230511/2차원배열-07-로봇이동.js
README.md

- 격자판 최대합, 스카이 라인, 봉우리, 로봇이동
---
- 격자판 최대합
- 각 행의 합의 최대값과 각 열의 합의 최대값
- 이중 for 문의 개별 원소값을 누적해서 더할 때마다, 0과 비교하며 최대값 찾음
- 각 양쪽 대각선의 합의 최대값
- for문의 개별 원소값을 누적해서 더할 때마다, 0과 비교하며 최대값 찾음
- 스카이 라인
- 앞쪽과 옆쪽 스카이라인 구하기(각 행과 열별 최대값 구하기)
- 이중 for 문의 개별 원소값을 0과 비교하며 최대값 생성, 각 행과 열별 최대값을 새로운 배열에 추가
- 증가시킬 수 있는 최대 높이의 합 구하기
- (이중 for 문의 개별 원소값) - (행의 최대값 배열과 열의 최대값 배열의 같은 index 중 더 작은 값) 을 누적하여 더함
- 봉우리
- 격자 가장자리 0으로 초기화
- Array().fill(0)과 unshift, push 사용하여 원래의 배열의 각 가장자리에 0을 추가하는 새로운 배열 생성
- 봉우리찾기
- 이중 for문의 개별 원소값이 상하좌우 보다 큰지 비교하여, 크면 1의 값 누적
- 로봇이동
- 답지참고
---

격자판 최대합, 스카이 라인, 봉우리, 로봇이동

---

LeeHyeRan/stack/5.11/index.js
index.html

- 올바른 괄호, 괄호문자제거, 연속된 문자 지우기, 쇠막대기
---
- 올바른 괄호, 괄호문자제거, 연속된 문자 지우기 push, pop 활용
- 쇠막대기 답지 참고했습니다!
---

올바른 괄호, 괄호문자제거, 연속된 문자 지우기, 쇠막대기

---

HanSooSan/230511.js

공주 구하기 , 최대 매출
---
주석 달았습니다.
(최대 매출은 답안 참고했습니다 !)
---

230512 알고리즘 풀이

---

LeeHyeRan/queue/05.12/index.js
LeeHyeRan/시간복잡도/05.12/index.js
LeeHyeRan/시간복잡도/05.13/index.js
index.html

- 공주 구하기 , 최대 매출
---
- 공주 구하기
while문 부터 답지 참고했습니다
- 최대 매출
이중 for문 사용
---

공주 구하기 , 최대 매출

---

LeeHyeRan/sorting/05.16/index.js

- 선택정렬, 버블정렬
---
- 버블정렬은 답지를 참고했습니다!
---

선택정렬, 버블정렬

---

HanSooSan/230511.js
HanSooSan/230512.js
HanSooSan/230515.js

카드 가져가기, 부분 수열, 공사 비용, 최대 길이 부분 수열, 연속된 자연수의 합
---
- 주석 참고
---

20230512 알고리즘 풀이

---

LeeHyeRan/sorting/05.17/index.js

- 삽입정렬, 교환횟수
---
- 주석 참고해주세요!
---

삽입정렬, 교환횟수

---

LeeHyeRan/sorting/05.18/index.js

- 카드가져가기, 이진수 정렬
---
- sort 메서드 활용
---

카드가져가기, 이진수 정렬

---

HanSooSan/230517.js

카드 가져가기, 이진수 정렬
---
주석 참고
이진수 정렬 while문 경우에는 답지를 참고했습니다.
---

230517 알고리즘 풀이

---

HanSooSan/230522.js

이분탐색, 랜선 자르기

---

LeeHyeRan/이분검색/06.07/index.js

- 초코볼, 데이터 센터
---
- 답지 안보고 풀고싶어서 이중포문을.. 많이 써버렸습니다ㅎㅅㅎ;;
- 이분 검색이 아닌 풀이여서 답지풀이도 함께 작성해 놓았습니다!
---

초코볼, 데이터센터

---

HanSooSan/230607.js

초코볼, 데이터 센터
---
풀다가 결국 이해 안 가서 강의 들으면서 해결했습니다 = 답지와 코드 같습니다 ㅠㅠ
---

초코볼, 데이터 센터

---

HanSooSan/230610.js

- 마구간, 타이타닉, 선긋기
---
- 강의 보면서 공부 중이기에 코드는 비슷합니다.
주석으로 설명 넣어 놨습니다.
---

마구간, 타이타닉, 선긋기

---

LeeHyeRan/greedy/06.12/index.js
LeeHyeRan/이분검색/06.08/index.js

- 마구간 정하기, 침몰하는 타이타닉, 선긋기, 회의실 배정
---
- 회의실 배정 제외 답지 참고했습니다!
---

마구간 정하기, 침몰하는 타이타닉, 선긋기, 회의실 배정

---

LeeHyeRan/greedy/06.13/index.js

- 이동횟수, 씨름선수
---
- 씨름선수 답지 참고했습니다!
---

이동횟수, 씨름선수

---

HanSooSan/230613.js

회의실 배경, 이동 횟수, 씨름 선수
---
greedy 알고리즘 주석 설명.
---

회의실 배경, 이동 횟수, 씨름 선수

---

LeeHyeRan/재귀함수/06.14/index.js
LeeHyeRan/재귀함수/06.15/index.js

- 재귀함수, 이진수출력, 조합의경우수,  중복순열 구하기
---
- 답지 참고했습니다!
---

재귀함수, 이진수출력, 조합의경우수, 중복순열 구하기

---

LeeHyeRan/재귀함수/06.23/index.js

- 순열 구하기, 피로도
---
- 두문제 다 답지 참고했습니다!
---

순열 구하기, 피로도

---

HanSooSan/230618.js

중복순열, 순열 구하기, 피로도

---

LeeHyeRan/array/06.26/index.js
LeeHyeRan/hashing/06.26/index.js
LeeHyeRan/stack/06.26/index.js

- 햄버거만들기, 삼총사, 숫자짝궁
---
- 숫자 짝궁 답지 참고했습니다!
---

햄버거만들기, 삼총사, 숫자짝궁

---

LeeHyeRan/array/06.28/index.js
LeeHyeRan/hashing/06.28/Index.js
LeeHyeRan/stack/06.28/index.js

- 신고결과받기, 키패드 누르기, 크레인 인형뽑기
---
- 거의 찾아보면서 풀었고 인형뽑기는 아직 미완료입니다..!
---

신고결과받기, 키패드 누르기, 크레인 인형뽑기

---

HanSooSan/2023 06 프로그래머스/신고결과받기.js
HanSooSan/2023 06 프로그래머스/크레인인형뽑기게임.js
HanSooSan/2023 06 프로그래머스/키패드누르기.js

- 신고결과받기, 키패드누르기, 크레인인형뽑기게임
---
- 주석
---

신고결과받기, 키패드누르기, 크레인인형뽑기게임

---

LeeHyeRan/greedy/06.29/index.js
LeeHyeRan/sorting/06.29/index.js

실패율, 체육복 수정

---

LeeHyeRan/sorting/07.01/index.js
LeeHyeRan/재귀함수/07.01/index.js

- 모의고사, k번째수
---
- 주석을 참고해주세요!
---

모의고사, k번째수

---

HanSooSan/2023 06 프로그래머스/두 큐 합 같게 만들기.js
HanSooSan/2023 06 프로그래머스/비밀지도.js
HanSooSan/2023 06 프로그래머스/완주하지 못한 선수.js
HanSooSan/2023 06 프로그래머스/제일 작은 수 제거하기
LeeHyeRan/array/07.03/index.js
LeeHyeRan/hashing/07.03/index.js

- 완주하지 못한 선수, 비밀지도
---
- 비밀지도 주석, 완주하지 못한 선수는 정렬해서 손 쉽게 풀었습니다.
---

완주하지 못한 선수, 비밀지도

---

LeeHyeRan/array/07.05/index.js
LeeHyeRan/queue/07.07/index.js

- 제일 작은 수 제거하기, 두 큐합 같게만들기
---
- for문으로 배열에 넣어주는 방식으로 풀었습니다!
- 두 큐합 같게 만들기는 투포인터 풀이방식 답안 참고했습니다!
---

제일 작은 수 제거하기, 두 큐합 같게만들기

---

LeeHyeRan/hashing/07.10/index.js
LeeHyeRan/stack/07.10/index.js

-  주차요금계산, 택배상자
---
- 주차요금계산은 더 풀어봐야 할 것 같습니다!
---

주차요금계산, 택배상자

---

LeeHyeRan/greedy/07.19/index.js

greedy - 거스름 돈 문제

---

LeeHyeRan/greedy/07.19/index.js

greedy 설탕배달

---

LeeHyeRan/이분검색/07.24/index.js

- binary search - 숫자 위치 찾기
---
- 주석 참고!
---

binary search - 숫자 위치 찾기

---

LeeHyeRan/이분검색/07.24/index.js

- binary search - 예산문제
---
- 주석 참고
---

binary search - 예산문제

---

LeeHyeRan/backtracking/07.26/index.js

- backtracking - n과 m 문제
---
- 주석 참고!
---

backtracking - n과 m 문제

---

LeeHyeRan/프로그래머스/Lv.2/JadenCase문자열만들기.js

JadenCase 문자열 만들기

---

LeeHyeRan/프로그래머스/Lv.1/로또의 최고 순위와 최저 순위.js

로또 최고 순위 최저 순위

---

LeeHyeRan/프로그래머스/Lv.1/숫자 문자열과 영단어.js

숫자 문자열과 영단어

---

LeeHyeRan/프로그래머스/Lv.1/없는숫자더하기.js
LeeHyeRan/프로그래머스/Lv.1/음양더하기.js

음양더하기, 없는숫자더하기

---

LeeHyeRan/프로그래머스/Lv.1/실패율.js
LeeHyeRan/프로그래머스/Lv.1/약수의 개수와 덧셈.js
LeeHyeRan/프로그래머스/Lv.1/포켓몬.js

약수의 개수와 덧셈, 포켓몬, 실패율

---

LeeHyeRan/프로그래머스/Lv.1/3진법 뒤집기.js
LeeHyeRan/프로그래머스/Lv.1/예산.js

3진법 뒤집기, 예산

---

LeeHyeRan/프로그래머스/Lv.1/2016년.js
LeeHyeRan/프로그래머스/Lv.1/두개뽑아서더하기.js

2016년, 두개뽑아서 더하기

---

LeeHyeRan/프로그래머스/Lv.1/부족한금액계산하기.js
LeeHyeRan/프로그래머스/Lv.1/최소직사각형.js

최소 직사각형, 부족한 금액 계산하기

---

LeeHyeRan/프로그래머스/Lv.1/가운데 글자가져오기.js
LeeHyeRan/프로그래머스/Lv.1/비밀지도.js

가운데 글자 가져오기, 비밀지도

---

LeeHyeRan/프로그래머스/Lv.1/같은숫자는싫어.js
LeeHyeRan/프로그래머스/Lv.1/나누어떨어지는숫자배열.js
LeeHyeRan/프로그래머스/Lv.1/두 정수 사이의합.js

- 같은 숫자는 싫어, 나누어 떨어지는 숫자, 두 정수 사이의 합
---

같은 숫자는 싫어, 나누어 떨어지는 숫자, 두 정수 사이의 합

---

LeeHyeRan/프로그래머스/Lv.1/문자열다루기.js
LeeHyeRan/프로그래머스/Lv.2/문자열압축.js

문자열 다루기, 문자열 압축

---

LeeHyeRan/프로그래머스/Lv.1/서울에서김서방찾기.js
LeeHyeRan/프로그래머스/Lv.2/오픈채팅방.js

서울에서 김서방찾기, 오픈채팅방

---

LeeHyeRan/프로그래머스/Lv.1/소수찾기.js
LeeHyeRan/프로그래머스/Lv.1/수박수박수.js

소수찾기, 수박수박수

---

LeeHyeRan/프로그래머스/Lv.1/시저암호.js
LeeHyeRan/프로그래머스/Lv.1/이상한문자만들기.js

시저암호, 이상한 문자 만들기

---

LeeHyeRan/프로그래머스/Lv.1/최대공약수최대공배수.js
LeeHyeRan/프로그래머스/Lv.1/콜라츠추측.js

최대공약수 최소공배수, 콜라츠추측

---

LeeHyeRan/프로그래머스/Lv.1/하샤드수.js
LeeHyeRan/프로그래머스/Lv.1/핸드폰번호가리기.js

하샤드수, 핸드폰번호 가리기

---

LeeHyeRan/프로그래머스/Lv.1/x만큼간격있는숫자.js
LeeHyeRan/프로그래머스/Lv.1/행렬의덧셈.js

행렬의 덧셈, x만큼간격있는 숫자

---

LeeHyeRan/프로그래머스/Lv.1/직사각형별찍기.js
LeeHyeRan/프로그래머스/Lv.1/크기가작은부분문자열.js

직사각형 별찍기, 크기가 작은 부분 문자열

---

LeeHyeRan/프로그래머스/Lv.1/가장가까운글자.js
LeeHyeRan/프로그래머스/Lv.1/푸드파이트대회.js

가장 가까운 글자, 푸드 파이트 대회

---

LeeHyeRan/프로그래머스/Lv.1/콜라문제.js
LeeHyeRan/프로그래머스/Lv.2/멀쩡한사각형.js

콜라문제, 멀쩡한 사각형
